"""Create update column in table 'order_items'

Revision ID: 21adf8e701e4
Revises: 38d3ab84bb19
Create Date: 2024-10-23 15:41:14.654505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21adf8e701e4'
down_revision = '38d3ab84bb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('order_items_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_order_id_fkey', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
