"""Add unique constraint to column 'name' of table 'pizzas'

Revision ID: 40000c8655a4
Revises: f459e5cdf897
Create Date: 2024-10-25 13:17:13.635944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40000c8655a4'
down_revision = 'f459e5cdf897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
