"""Create table 'pizza_sizes'

Revision ID: 8685d94de76d
Revises: a4720fb31edd
Create Date: 2024-10-23 13:28:40.217825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8685d94de76d'
down_revision = 'a4720fb31edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('s', 'm', 'l', 'j', name='sizeenum'), nullable=False),
    sa.Column('grammage', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pizza_id', 'size')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza_sizes')
    sa.Enum('s', 'm', 'l', 'j', name='sizeenum').drop(op.get_bind())
    # ### end Alembic commands ###
