"""Update column in table 'pizza_sizes'

Revision ID: f459e5cdf897
Revises: 21adf8e701e4
Create Date: 2024-10-24 09:14:21.015487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f459e5cdf897'
down_revision = '21adf8e701e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza_sizes', schema=None) as batch_op:
        batch_op.drop_constraint('pizza_sizes_pizza_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza_sizes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pizza_sizes_pizza_id_fkey', 'pizzas', ['pizza_id'], ['id'])

    # ### end Alembic commands ###
